# Generated by Django 5.0.6 on 2024-09-10 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('checkNumber', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Check Number')),
                ('fname', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('lname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('bankName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number')),
                ('grossAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Gross Amount')),
                ('basicSalary', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Basic Salary')),
                ('netAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Net Amount')),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Allowance')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Region Name')),
                ('registered_date_auto', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
            ],
            options={
                'verbose_name': 'Mkoa',
                'verbose_name_plural': 'Mkoa',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('check_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('simu', models.BigIntegerField(unique=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region', verbose_name='Region')),
            ],
        ),
    ]
