# Generated by Django 5.0.6 on 2024-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='region',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterField(
            model_name='person',
            name='check_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='simu',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
