# Generated by Django 5.0.6 on 2024-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_person_region_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='registered_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='simu',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone number'),
        ),
    ]
