# Generated by Django 5.0.6 on 2024-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_person_options_remove_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
