# Generated by Django 5.0.6 on 2024-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UraMember',
            fields=[
                ('check_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ura_id', models.CharField(max_length=50, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(max_length=100)),
            ],
        ),
    ]
