# Generated by Django 5.0.6 on 2024-09-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_uramember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UraMember',
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
