# Generated by Django 5.0.6 on 2024-09-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_personreset_options_alter_personreset_simu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
