# Generated by Django 5.0.6 on 2024-09-30 06:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
