# Generated by Django 5.0.6 on 2024-11-07 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_person_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District Name')),
                ('registered_date_auto', models.DateTimeField(auto_now_add=True, unique=True, verbose_name='Registered Date')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'District',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Post Name')),
                ('registered_date_auto', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Region Name')),
                ('registered_date_auto', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True, verbose_name='Employee Role')),
                ('registered_date_auto', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='Upload Ura mobile form'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
                ('force_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Force Number')),
                ('rank', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rank')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.district', verbose_name='District')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Post')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region', verbose_name='Region')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.role', verbose_name='user_role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
