# Generated by Django 5.0.6 on 2024-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_district_post_region_role_alter_person_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
