# Generated by Django 5.0.6 on 2024-11-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_person_user_personreset_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'New Mobile Users', 'verbose_name_plural': 'New Mobile Users'},
        ),
        migrations.AlterModelOptions(
            name='personreset',
            options={'verbose_name': 'Pin Reset Users', 'verbose_name_plural': 'Pin Reset Users'},
        ),
    ]
