# Generated by Django 5.0.6 on 2024-11-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_branch_remove_employee_region_employee_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.AddField(
            model_name='district',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.district', verbose_name='District'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.role', verbose_name='user_role'),
            preserve_default=False,
        ),
    ]
